'use client';
import {publicUrl} from '@/lib/public-url';
import f1 from '@/lib/f1.json';
import audit from '@/lib/audit.json';
import {cases,study,zones,fmt,radii} from '@/lib/study';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Download,ArrowUpRight,Check} from 'lucide-react';
export function DataTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table>}
export function Evidence({onChoose}:{onChoose:(id:string)=>void}){return <div className="evidence-wrap"><div className="section-heading"><div><div className="eyebrow">DESIGN ARGUMENT / 01–03</div><h2>让结论与前提一起出现。</h2><p>三个示例均来自同一份 F1 方案。先看空间事实，再比较有条件的流程提议。</p></div><a className="download-link" href={publicUrl('/f1-study-report.md')} download><Download/>完整报告</a></div><div className="evidence-cards">{cases.map((x,i)=>{const s=study(x.id,x.radius,x.speed);return <section key={x.id} className="panel evidence-card"><div className="card-kicker"><span>0{i+1}</span><span>{x.tag}</span></div><h2>{x.title}</h2><p>{x.description}</p><div className="comparison-bars">{[['A',s.a.distanceM],['B',s.b.distanceM]].map(([v,n])=><div key={String(v)}><span>{v}</span><div><i className={v==='b'?'b-bar':''} style={{width:`${(n as number)/200*100}%`}}/></div><b>{fmt(n as number)} m</b></div>)}</div><div className="card-delta">少走 <b>{fmt(s.savedM)} m</b><span> / {fmt(s.percent)}%</span></div><dl><dt>路径情景前提</dt><dd>{x.condition}</dd><dt>设计提议及条件</dt><dd>{x.proposal}</dd><dt>仍需确认</dt><dd>{x.pending}</dd></dl><Button variant="outline" onClick={()=>onChoose(x.id)}>在图上查看<ArrowUpRight/></Button><p className="footnote">圆盘半径 {x.radius} mm；假设速度 {x.speed} m/min。A/B 只改变现场办理节点，其余相同。</p></section>})}</div>
 <section className="panel evidence-section"><div className="section-heading"><div><h2>包络敏感性：路径会随净空约束改变</h2><p>同一节点顺序，分别计算 100–450 mm 圆盘半径。单位：m；以下均为 A 路径。</p></div><a className="download-link" href={publicUrl('/scenario-results.csv')} download>24 组 A/B 比较 CSV <Download size={16}/></a></div><div className="sensitivity-grid"><DataTable headers={['半径',...cases.map(x=>x.short)]} rows={radii.map(r=>[`${r} mm`,...cases.map(x=>fmt(study(x.id,r,x.speed).a.distanceM,3))])}/><div className="reasoning-note"><b>如何解释“都能到达”</b><p>本模型 13 个公共节点，在八个测试半径下均连通。连通只说明固定障碍和圆盘模型下存在路线，不能推导轮椅转弯、门禁或动态拥堵满足要求。</p><b>什么数据最值得补充</b><p>优先核对现场办理规则、真实起终点与门开启条件，再补患者路径样本。仅为三种情景等权平均，没有运营意义。</p></div></div></section>
 <section className="panel evidence-section"><div className="section-heading"><div><h2>空间事实，也要保持正确口径</h2><p>按原文件的房间净面积汇总，不将其余面积自动解释为走廊或“低效空间”。</p></div></div><div className="area-grid"><div>{Object.entries(zones).map(([k,z])=>{const rs=f1.model.rooms.filter(r=>r.zone===k),area=rs.reduce((a,r)=>a+r.area_m2,0);return <div className="area-row" key={k}><span>{z.name}<small>{rs.length} 间</small></span><div><i style={{width:`${area/600*100}%`,background:z.color}}/></div><b>{area.toFixed(1)} ㎡</b></div>})}</div><div className="reasoning-note"><b>3996.5 ㎡</b><p>文件所列轮廓面积。另列上空 229.6 ㎡、房间净面积合计 1797.9 ㎡，三者定义不同，不能直接当作审定建筑面积或面积效率指标。</p><b>69 候诊席 + 7 轮椅预留位</b><p>来自家具布置假设。没有到达率与停留数据，尚不能论证候诊容量足够。</p></div></div></section></div>}
export function SourceData({onRoom}:{onRoom:(id:string)=>void}){return <div className="evidence-wrap"><section className="panel evidence-section"><div className="section-heading"><div><div className="eyebrow">SOURCE OF TRUTH</div><h2>每条数据，保留来源与边界。</h2><p>原文件状态：{f1.provenance.status}。导入于 {f1.provenance.importedAt}。</p></div><a className="download-link" href={publicUrl('/source-f1.html')} target="_blank" rel="noreferrer">查看原文件<ArrowUpRight size={16}/></a></div><DataTable headers={['数据层','已提供 / 已计算','解释范围']} rows={[
 ['平面几何','76 房间、58 墙多边形、93 门洞、74 柱、38 窗','文件自述源自 V01 CAD 草图重建；原始 CAD、图签与现场尺寸未提供核验。'],
 ['房间与设施','DR / CT / MRI 及配套；诊区、功能检查与支持用房','带 * 的用途及部分服务点暂拟；不能替换成另一家医院名称。'],
 ['家具与高度','219 家具对象、69 候诊席、7 轮椅预留位；层高 4.2 m','均含方案假设；高度改变不会自动更新本页的固定公共净空场。'],
 ['导航底座','200 mm 公共净空栅格、13 个到达节点','门按有效开启；家具外包络固定；受控空间和房内移动未纳入。'],
 ['本次重算',`${audit.pairRuns} 条有序节点路线，24 组 A/B 情景比较`,'8 种圆盘半径；含节点自身到自身的 0 m 路线。不是随机仿真样本量。'],
 ['项目身份','项目名称、院区、规模、设计单位及图纸阶段待确认','“综合医院”是项目研究方向，目前不能认定为某家已建医院的现状。'],
 ['全院组织','总平面、楼层关系、病房、急诊、手术、ICU、消毒供应未提供','未建模不代表医院没有这些部门；不推算全院流线或洁污分离结论。'],
 ['运营事实','预约、到达、服务时长、医护排班、门禁和电梯参数待确认','不报告真实排队、接诊能力、医疗响应、人员负荷或就诊总时间。']
 ]}/></section><div className="method-grid"><section className="panel evidence-section"><h2>可复核的计算链</h2><ol className="method-list"><li><b>读取几何与公共净空场</b><p>保留源文件毫米坐标和 13 个已定位公共节点，净空场已包含家具等固定障碍。</p></li><li><b>在可通行栅格上搜索</b><p>复用内嵌 Navigator：八邻接 Dijkstra，禁止斜切角；不借道诊室、机房或后台。仅压缩共线点。</p></li><li><b>核查并汇总路径链</b><p>检查每个经过栅格与转角，按节点顺序累加各段。任一段不通则整条情景不可达，不将失败段计为 0 m。</p></li><li><b>相同条件下比较 A/B</b><p>B 只略过现场办理点；半径与速度相同。纯移动时间 = 路程 ÷ 假设速度。</p></li></ol></section><section className="panel evidence-section"><h2>已执行的核查</h2><div className="audit-line"><Check/><span>{audit.baselineChecks} 项 300 mm 基准核对</span></div><div className="audit-line"><Check/><span>{audit.stepChecks.toLocaleString()} 次相邻步与斜角检查</span></div><div className="audit-line"><Check/><span>{audit.symmetryChecks} 项距离对称检查</span></div><div className="audit-line"><Check/><span>{audit.monotonicChecks} 项包络收紧检查</span></div><p>与原文件基准矩阵的最大差值 {fmt(audit.maxBaselineErrorMeters*1000,3)} mm，来自基准保存时的小数舍入。基准一致不等同于现场精度验证。</p><div className="download-grid"><a href={publicUrl('/route-matrix.csv')} download>完整节点距离 CSV<Download size={16}/></a><a href={publicUrl('/scenario-results.json')} download>情景与逐段路线 JSON<Download size={16}/></a><a href={publicUrl('/audit.json')} download>计算核查记录 JSON<Download size={16}/></a><a href={publicUrl('/f1-study-report.md')} download>三组论证报告<Download size={16}/></a></div></section></div>
 <section className="panel evidence-section"><div className="section-heading"><div><h2>76 个房间的原始清单</h2><p>面积采用源文件 area_m2；坐标单位 mm；点击房间编号回到平面查看。</p></div></div><DataTable headers={['编号','名称','功能区','原文件净面积','矩形坐标范围']} rows={f1.model.rooms.map(r=>[<Button key={r.id} variant="link" onClick={()=>onRoom(r.id)}>{r.id}<ArrowUpRight size={13}/></Button>,r.name,zones[r.zone].name,`${r.area_m2} ㎡`,`(${r.rect[0]}, ${r.rect[1]}) – (${r.rect[2]}, ${r.rect[3]})`])}/><p className="fingerprint">源文件 SHA-256：{f1.provenance.sha256}</p></section></div>}
