'use client';
import {useState} from 'react';
import {SourceImage,svgImageFallback} from './source-image';
import {type Hospital,type Journey,type Floor,journeyStats} from '@/lib/projects';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Layers3,FileImage,ArrowUpRight,ArrowRight,Minus,Plus,Focus,MoveVertical} from 'lucide-react';
const kindColors={public:'#087f99',bed:'#c98425',logistics:'#8061a8'};
function OriginalImage({src,alt}:{src:string;alt:string}){const [zoom,setZoom]=useState(1);return <><div className="image-toolbar"><span>原始资料图 · 可缩放查看</span><div><Button size="icon" variant="ghost" aria-label="缩小图纸" onClick={()=>setZoom(Math.max(1,zoom-.5))}><Minus/></Button><b>{zoom.toFixed(1)}×</b><Button size="icon" variant="ghost" aria-label="放大图纸" onClick={()=>setZoom(Math.min(4,zoom+.5))}><Plus/></Button><Button size="icon" variant="ghost" aria-label="恢复整张图纸" onClick={()=>setZoom(1)}><Focus/></Button><a href={src} target="_blank" rel="noreferrer" aria-label="独立窗口查看原图"><ArrowUpRight size={17}/></a></div></div><div className="original-scroll"><SourceImage src={src} alt={alt} style={{width:`${zoom*100}%`,maxWidth:'none'}}/></div></>}
export function FloorModel({h,floor,journey,onFloor}:{h:Hospital;floor:Floor;journey:Journey;onFloor:(n:number)=>void}){
 const [view,setView]=useState('stack'),[gap,setGap]=useState(39);const sorted=[...h.floors].sort((a,b)=>a.level-b.level),height=Math.max(620,sorted.length*gap+260),color=kindColors[journey.kind];
 const y=(n:number)=>height-240-sorted.findIndex(f=>f.level===n)*gap;
 return <section className="panel multi-canvas"><div className="panel-title"><Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList><TabsTrigger value="stack"><Layers3 size={15}/>楼层叠览</TabsTrigger><TabsTrigger value="plan"><FileImage size={15}/>本层原图</TabsTrigger><TabsTrigger value="section">{h.section?'剖面':'病区资料'}</TabsTrigger>{h.id==='nanjing'&&<TabsTrigger value="site">总平面</TabsTrigger>}</TabsList></Tabs><span>{h.id==='hongkong'?'6 个已核实功能层级':'公开图纸分层'}</span></div>
 {view==='stack'?<><div className="stack-controls"><span>展开间距 <small>仅调整显示</small></span><Slider aria-label="楼层叠览显示间距" value={[gap]} min={25} max={60} step={1} onValueChange={v=>setGap(Array.isArray(v)?v[0]:v)}/><span className="route-key" style={{color}}><i style={{background:color}}/>{journey.kind==='public'?'公共联系':journey.kind==='bed'?'推床联系':'物流联系'}</span></div><svg viewBox={`0 0 930 ${height}`} className="stack-svg" aria-label={`${h.name}楼层组织及${journey.title}示意`}>
 <defs><marker id="vertical-arrow" markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M1 1L5 3.5L1 6" fill="none" stroke={color} strokeWidth="1.3"/></marker></defs>
 {sorted.map(f=><g key={f.level} role="button" tabIndex={0} aria-label={`查看${f.label} ${f.title}`} onClick={()=>onFloor(f.level)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onFloor(f.level)}}}>
 {f.image?<g transform={`matrix(.88 .14 -.4 .3 328 ${y(f.level)})`}><rect width="528" height="373" fill="white" stroke={f.level===floor.level?'#0798b5':'#bfccd5'} strokeWidth={f.level===floor.level?4:1}/><image onError={svgImageFallback} href={f.image} width="528" height="373" preserveAspectRatio="xMidYMid meet" opacity={f.level===floor.level?1:.55}/></g>:<g transform={`translate(250 ${y(f.level)+100})`}><rect x="0" y="0" width="435" height="40" rx="5" fill={f.status==='unknown'?'#e3eaf0':'#d6e8ee'} stroke={f.level===floor.level?'#0a849c':'#bfccd5'} strokeDasharray={f.status==='unknown'?'5 5':undefined}/><text x="18" y="25" fill="#547583" fontSize="13">{f.title} · {f.status==='unknown'?'功能待核实':'功能关系层 / 无完整平面'}</text></g>}
 <path d={`M65 ${y(f.level)+140}H185`} stroke={f.level===floor.level?'#087f99':'#a7bcc9'} strokeWidth={f.level===floor.level?2:1}/><text x="22" y={y(f.level)+145} fill={f.level===floor.level?'#087f99':'#597382'} fontSize="16" fontWeight="650">{f.label}</text><text x="65" y={y(f.level)+132} fill="#597382" fontSize="12">{f.title}</text></g>)}
 {journey.floors.slice(1).map((n,i)=><path key={i} d={`M${760+i*18} ${y(journey.floors[i])+125}V${y(n)+125}`} stroke={color} strokeWidth="3" fill="none" opacity=".8" markerEnd="url(#vertical-arrow)"/>)}
 {[...new Set(journey.floors)].map(n=><g key={n}><circle cx="750" cy={y(n)+125} r="6" fill={color}/><path d={`M685 ${y(n)+125}H745`} stroke={color} strokeWidth="1.5" strokeDasharray="4 4"/></g>)}
 <text x="40" y={height-22} fill="#6b8594" fontSize="12">图纸未做几何配准；展开间距不是实际层高。连线表达跨层联系，不定位实际梯井。</text></svg></>:view==='plan'?(floor.image?<OriginalImage key={floor.image} src={floor.image} alt={`${h.name} ${floor.label} 原始图纸`}/>:<div className="no-plan"><FileImage size={35}/><h2>{floor.label} · {floor.title}</h2><p>未获取本层可核验平面，以下只列公开资料支持的功能。</p><div>{floor.functions.map(t=><span key={t}>{t}</span>)}</div><p>不使用其他层图纸填充该楼层。</p></div>):view==='site'?<OriginalImage src="/projects/nanjing/site.jpg" alt="南京鼓楼医院南扩总图，门诊、医技、住院体块及不同出入口"/>:<OriginalImage key={h.id} src={h.section??'/projects/hongkong/ward.png'} alt={h.section?`${h.name}建筑师公开剖面`:'香港中文大学医院历史病区分区图'}/>}
 <div className="drawing-credit">{view==='section'&&h.id==='dushu'?'剖面为建筑师发表版本，不能与验收平面视为同一竣工图。':h.id==='dushu'?'主平面：2021 验收报告附图（消防栓分布图），按楼层分别保留。':h.id==='nanjing'?'图纸 © LEMANARC；2012 建成项目发表资料，后期科室变化另列。':'病区图：Hong Fung 2024 演讲第27页，疫情分区历史状态。'}<span>{view==='plan'&&floor.level>=7&&h.id==='nanjing'?'标准层参考图；具体楼层变体未核验。':''}</span></div>
 <div className="journey-strip"><div><b>{journey.title}</b><span><MoveVertical size={13}/>{journeyStats(journey).rides} 次换层联系</span></div><div className="journey-stops">{journey.floors.map((n,i)=><span key={i}><Button variant={floor.level===n?'secondary':'ghost'} onClick={()=>onFloor(n)}>{journey.labels[i]}</Button>{i<journey.floors.length-1&&<ArrowRight size={13}/>}</span>)}</div><p>{journey.note}</p></div>
 </section>
}

