'use client';
import {publicUrl} from '@/lib/public-url';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {hospitals,hospital,type Hospital,type Source} from '@/lib/projects';
import {experiment,DEFAULTS,validateOptions,type Options} from '@/lib/vertical-sim';
import {FloorModel} from './floor-model';
import {ModelWorkspace} from './model-workspace';
import {VerticalExperiment,initialExperiment,type Experiment} from './vertical-experiment';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DataTable} from './evidence';
import {Building2,ArrowUpRight,Download,Layers3,ArrowUpDown,BookOpen,Route,ExternalLink,Check} from 'lucide-react';
import './multifloor.css';
export default function MultiWorkspace(){
 const [id,setId]=useState('dushu'),[level,setLevel]=useState(1),[journeyId,setJourneyId]=useState('outpatient'),[tab,setTab]=useState('furnished'),[result,setResult]=useState<Experiment>(initialExperiment('dushu'));
 const h=hospital(id),floor=h.floors.find(f=>f.level===level)??h.floors[0],journey=h.journeys.find(j=>j.id===journeyId)??h.journeys[0];
 const revision=useRef(0);
 const selectProject=(nextId:string)=>{revision.current++;const n=hospital(nextId);setId(nextId);setLevel(n.ground);setJourneyId('outpatient');setResult(initialExperiment(nextId));};
 const run=async(o:Options)=>{validateOptions(o);const token=++revision.current;await new Promise(r=>setTimeout(r,40));const next=experiment(id,o);if(token===revision.current)setResult(next);};
 const api=useRef({id,level,result,selectProject});api.current={id,level,result,selectProject};
 useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as unknown as {modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('Multi-floor tool registration',e));}catch(e){console.warn(e)}};
 const short=(e:Experiment)=>({project:e.id,options:e.options,a:e.a,b:e.b,pairedDelta:e.delta,scope:'Public floor facts + hypothetical transport model, not observed hospital operations.'});
 register({name:'get_multifloor_study',title:'读取多层医院研究',description:'读取当前真实项目、选择楼层、公开来源和已执行的假设运行对照。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('仅接受空对象');return {floor:api.current.level,sources:hospital(api.current.id).sources,...short(api.current.result)}}});
 register({name:'run_multifloor_transport',title:'运行跨层交通对照',description:'选择项目并使用假设参数执行12组A/B配对计算，更新可见实验页面。',inputSchema:{type:'object',properties:{projectId:{type:'string',enum:hospitals.map(x=>x.id)},fleet:{type:'integer',minimum:2,maximum:8},dedicated:{type:'integer',minimum:1,maximum:7},demand:{type:'number',minimum:.4,maximum:2},floorSeconds:{type:'number',minimum:2,maximum:10},publicPerHour:{type:'number',minimum:60,maximum:1200},bedPerHour:{type:'number',minimum:4,maximum:120}},required:['projectId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('参数格式错误');const x=input as Record<string,unknown>;if(typeof x.projectId!=='string'||Object.keys(x).some(k=>!['projectId',...Object.keys(DEFAULTS)].includes(k)))throw Error('未知参数');hospital(x.projectId);const options={...DEFAULTS,...Object.fromEntries(Object.entries(x).filter(([k])=>k!=='projectId'))} as Options;validateOptions(options);await new Promise(r=>setTimeout(r,0));const e=experiment(x.projectId,options);flushSync(()=>{api.current.selectProject(e.id);setResult(e);setTab('analysis');});return short(e)}});return()=>lifecycle.abort();},[]);
 return <main className="multi-lab"><header className="topbar"><div className="brand"><Building2/><strong>综合医院<span>多层设计研究</span></strong></div><div className="top-actions"><a href={publicUrl('/f1/')}>用户 F1 局部模型<ArrowUpRight size={15}/></a><a className="report-top" href={publicUrl('/multifloor-study.md')} download><Download size={15}/>研究报告</a></div></header>
 <div className="project-switcher">{hospitals.map((p,i)=><Button key={p.id} variant="ghost" className={`project-option ${p.id===id?'selected':''}`} aria-pressed={p.id===id} onClick={()=>selectProject(p.id)}><span className="project-index">0{i+1}</span><div><b>{p.short}</b><span>{p.city} · {p.bedLabel} · {p.tag}</span></div><ArrowUpRight size={17}/></Button>)}</div>
 <div className="multi-title"><div><div className="eyebrow">REAL PROJECT / {h.phase}</div><h1>{h.name}</h1><p>{h.scope}</p></div><div className="multi-facts"><span><b>{h.bedLabel}</b>公开建设口径</span><span><b>{h.areaLabel}</b>工程建筑面积</span><span><b>{h.floors.filter(f=>f.status!=='unknown').length}</b>有资料的功能层级</span></div></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))} className="multi-main-tabs"><div className="tab-bar"><TabsList variant="line"><TabsTrigger value="furnished"><Building2/>三维建模与家具</TabsTrigger><TabsTrigger value="model"><Layers3/>多层组织与图纸</TabsTrigger><TabsTrigger value="analysis"><ArrowUpDown/>跨层运行实验</TabsTrigger><TabsTrigger value="evidence"><BookOpen/>三院比较与证据</TabsTrigger></TabsList><span className="verified"><Check size={14}/>公开来源 + 216 次默认情景仿真</span></div>
 <TabsContent value="furnished"><ModelWorkspace key={id} h={h} onLevel={setLevel}/></TabsContent><TabsContent value="model"><div className="multi-grid"><aside className="panel floor-sidebar"><div className="eyebrow">楼层导航</div>{[...h.floors].reverse().map(f=><Button key={f.level} variant={floor.level===f.level?'default':'ghost'} className={`floor-button ${f.status==='unknown'?'unconfirmed':''}`} onClick={()=>setLevel(f.level)}><b>{f.label}</b><span>{f.title}</span></Button>)}<div className="floor-legend"><i/>有资料 <i className="unknown-dot"/>待核实</div></aside><div className="model-center"><div className="journey-picker"><span><Route size={15}/>联系情景</span>{h.journeys.map(j=><Button key={j.id} size="sm" variant={journeyId===j.id?'default':'outline'} onClick={()=>setJourneyId(j.id)}>{j.title}</Button>)}</div><FloorModel key={id} h={h} floor={floor} journey={journey} onFloor={setLevel}/></div><aside className="panel floor-inspector"><div className="eyebrow">SELECTED FLOOR / {floor.label}</div><h2>{floor.title}</h2><span className={`evidence-badge ${floor.status==='unknown'?'muted':''}`}>{floor.status==='unknown'?'功能资料待补充':floor.status==='partial'?'部分信息已核实':'有直接资料支持'}</span><ul className="department-list">{floor.functions.map(t=><li key={t}>{t}</li>)}</ul>{floor.height!==undefined&&<p className="known-height">剖面标高 <b>+{floor.height.toFixed(2)} m</b></p>}{floor.note&&<p className="floor-caveat">{floor.note}</p>}<div className="source-card"><b>该层资料依据</b>{floor.sources.map(sid=>{const s=h.sources.find(s=>s.id===sid)!;return <SourceLink key={sid} s={s}/>})}</div><div className="source-card"><b>全院组织要点</b>{h.notes.map(n=><p key={n}>{n}</p>)}</div><Button variant="outline" className="inspect-analysis" onClick={()=>setTab('analysis')}>执行跨层对照<ArrowUpRight size={15}/></Button></aside></div></TabsContent>
 <TabsContent value="analysis"><VerticalExperiment key={`${id}-${result.options.fleet}-${result.options.dedicated}-${result.options.demand}-${result.options.floorSeconds}-${result.options.publicPerHour}-${result.options.bedPerHour}`} h={h} result={result} onRun={run}/></TabsContent>
 <TabsContent value="evidence"><EvidenceDirectory onSelect={next=>{selectProject(next);setTab('model')}}/></TabsContent></Tabs><footer className="lab-footer"><span>公开真实项目 / 多层综合医院研究</span><span>资料版本可查 · 运行参数为假设 · 结果可复算</span><span>2026.09</span></footer></main>
}
function SourceLink({s}:{s:Source}){return <div className="source-item"><a href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={13}/></a><small>{s.kind} · {s.date}</small></div>}
function EvidenceDirectory({onSelect}:{onSelect:(id:string)=>void}){return <div className="multi-evidence"><div className="section-heading"><div><div className="eyebrow">EVIDENCE / COMPARISON</div><h2>三个项目，三种资料完整度。</h2><p>先比较组织与证据范围。模型的假设结果用于方案试验，不做医院运营排名。</p></div><a className="download-link" href={publicUrl('/multifloor-study.md')} download><Download size={16}/>完整研究报告</a></div><div className="project-evidence-grid">{hospitals.map(h=><section className="panel project-evidence-card" key={h.id}><span>{h.city} / {h.phase}</span><h2>{h.short}</h2><p>{h.tag}</p><dl><dt>可展示的真实空间</dt><dd>{h.id==='dushu'?'B1、1–7F、8–11F及12F分别有验收报告附图；B2功能可查。':h.id==='nanjing'?'1–3F、7–14F标准层、总图与剖面；4–6F不复制其他层补图。':'G/F、1/F、2/F、3/F、5/F、7/F有官方功能依据；病区图有历史版本说明。'}</dd><dt>当前不能推出</dt><dd>{h.id==='dushu'?'图上全部房间坐标与实际净宽；建筑发表图和验收图不能混为同一版。':h.id==='nanjing'?'2012各层科室与2022/2025改造的一一空间对应；核准不等于已实施。':'未公开楼层的平面、编号与面积；病区历史分区不等于当前门禁。'}</dd></dl><Button variant="outline" onClick={()=>onSelect(h.id)}>查看楼层与原图<ArrowUpRight size={15}/></Button></section>)}</div>
 <section className="panel transport-detail"><h2>默认跨层实验：保留不利结果</h2><p>三小时假设请求，4台共享服务池 A，对照 1床梯+3公众梯的 B；12配对种子。单位：秒。</p><DataTable headers={['项目','公众 P90 A → B','推床 P90 A → B','推床 B−A 95%区间']} rows={hospitals.map(h=>{const e=initialExperiment(h.id);return [h.short,`${e.a.publicP90.toFixed(1)} → ${e.b.publicP90.toFixed(1)}`,`${e.a.bedP90.toFixed(1)} → ${e.b.bedP90.toFixed(1)}`,`[${e.delta.bedP90.low.toFixed(1)}, ${e.delta.bedP90.high.toFixed(1)}]`];})}/><p className="footnote">上述差异来自假设需求、已选功能楼层和简化调度规则；三院资料覆盖及标高依据不同，不能据数值判断哪家医院设计更优。</p><div className="evidence-downloads"><a href={publicUrl('/multifloor-results.csv')} download>216 次运行 CSV<Download size={15}/></a><a href={publicUrl('/multifloor-results.json')} download>参数与配对结果 JSON<Download size={15}/></a><a href={publicUrl('/multifloor-audit.json')} download>核查记录 JSON<Download size={15}/></a></div></section>
 <section className="panel transport-detail"><h2>从案例研究走向项目论证，还需补齐</h2><div className="needed-data">{[['空间','带尺度 CAD/BIM、原始轴网、各层房间与门、梯井及停靠层。'],['权限','公共、推床、员工、清洁物资、标本、污物各自的通行规则。'],['需求','按时段的起终点请求、陪同与床转运比例、预约波峰及服务释放。'],['校准','真实候梯与乘行样本、梯速/载荷、门周期及运行控制方式。']].map(([t,s])=><div key={t}><b>{t}</b><p>{s}</p></div>)}</div><p className="footnote">原 F1 精细网格模型保留在“用户 F1 局部模型”中；没有将该平面复制到三家医院。</p></section>
 {hospitals.map(h=><section key={h.id} className="panel transport-detail source-ledger"><div className="section-heading"><div><h2>{h.short} · 来源记录</h2><p>{h.scope}</p></div></div><DataTable headers={['资料','时间 / 类型','用于说明什么']} rows={h.sources.map(s=>[<a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={13}/></a>,`${s.date} · ${s.kind}`,s.note])}/></section>)}</div>}


