'use client';
import {useEffect,useImperativeHandle,useRef,useState,forwardRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {buildPlanScene,exportableScene,type SceneOptions,type PickInfo} from '@/lib/plan-scene';
import {type PlanModel,modelBounds,downloadData,isCirculation,furnitureNames,furnishingDetail} from '@/lib/plan-model';
export type ViewerHandle={view:(mode:'iso'|'top'|'zoomIn'|'zoomOut'|'left'|'right')=>void;focus:(id:string)=>void;exportGlb:()=>Promise<void>};
type Props={model:PlanModel;options:SceneOptions;onPick:(p:PickInfo|null)=>void};
export const PlanViewer=forwardRef<ViewerHandle,Props>(function PlanViewer({model,options,onPick},ref){
 const host=useRef<HTMLDivElement>(null),[error,setError]=useState(''),pick=useRef(onPick);pick.current=onPick;
 const engine=useRef<{scene:THREE.Scene;camera:THREE.OrthographicCamera;controls:OrbitControls;renderer:THREE.WebGLRenderer;built:ReturnType<typeof buildPlanScene>|null;reset:(mode:'iso'|'top')=>void;request:()=>void;size:number}|null>(null);
 useImperativeHandle(ref,()=>({view(mode){const e=engine.current;if(!e)return;if(mode==='iso'||mode==='top')e.reset(mode);else if(mode==='zoomIn'||mode==='zoomOut'){e.camera.zoom=THREE.MathUtils.clamp(e.camera.zoom*(mode==='zoomIn'?1.35:1/1.35),.3,25);e.camera.updateProjectionMatrix()}else{const offset=e.camera.position.clone().sub(e.controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),mode==='left'?.26:-.26);e.camera.position.copy(e.controls.target).add(offset)}e.controls.update();e.request()},focus(id){const e=engine.current;if(!e?.built)return;const room=model.rooms.find(r=>r.id===id),facility=model.furniture.find(f=>f.id===id&&isCirculation(f.type));if(!room&&!facility)return;const x=facility?facility.x:room!.polygon.reduce((s,p)=>s+p[0],0)/room!.polygon.length,y=facility?facility.y:room!.polygon.reduce((s,p)=>s+p[1],0)/room!.polygon.length;const target=new THREE.Vector3((x-e.built.center.x)*e.built.scale,0,(y-e.built.center.y)*e.built.scale),delta=target.clone().sub(e.controls.target);e.controls.target.copy(target);e.camera.position.add(delta);e.camera.zoom=facility?Math.min(18,Math.max(5,e.size/(Math.max(facility.w,facility.d)*model.unitsPerPixel*3))):3.5;e.camera.updateProjectionMatrix();e.controls.update();e.request();pick.current(facility?{kind:'circulation',id:facility.id,label:furnitureNames[facility.type],evidence:facility.evidence,furnitureType:facility.type,roomId:facility.roomId,detail:furnishingDetail(facility)}:{kind:'room',id:room!.id,label:room!.label,evidence:room!.evidence,detail:'房间边界参考源图；未进行净面积或通行校核。'})},async exportGlb(){const e=engine.current;if(!e?.built)throw Error('模型尚未加载');const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const out=exportableScene(e.built.root);const result=await new GLTFExporter().parseAsync(out,{binary:true,onlyVisible:true});if(!(result instanceof ArrayBuffer))throw Error('模型导出失败');downloadData(result,model.id+'-study.glb','model/gltf-binary');}}),[model]);
 useEffect(()=>{const element=host.current;if(!element)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});setError('')}catch{setError('当前设备未能启动三维显示。可切换“描图核对”查看模型平面与家具。');return;}
  const scene=new THREE.Scene();scene.background=new THREE.Color('#e8eff3');const b=modelBounds(model),size=Math.max(b.maxX-b.minX,b.maxY-b.minY)*model.unitsPerPixel;
  const camera=new THREE.OrthographicCamera(-size/2,size/2,size/2,-size/2,.1,size*12);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.screenSpacePanning=true;controls.maxPolarAngle=Math.PI/2-.015;controls.minZoom=.3;controls.maxZoom=25;
  renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.setAttribute('aria-label',`${model.label} 可旋转三维模型。拖动旋转，右键拖动平移，滚轮缩放；也可使用下方视角按钮。`);renderer.domElement.setAttribute('role','img');element.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight('#ffffff','#9cabb8',2.4));const sun=new THREE.DirectionalLight('#fffaf0',2.7);sun.position.set(-size*.3,size*.9,-size*.4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-size*.75;sun.shadow.camera.right=size*.75;sun.shadow.camera.top=size*.75;sun.shadow.camera.bottom=-size*.75;sun.shadow.camera.far=size*3;sun.shadow.normalBias=.045;sun.shadow.bias=-.0002;scene.add(sun);const fill=new THREE.DirectionalLight('#c8e4f3',.8);fill.position.set(size*.5,size*.5,size*.5);scene.add(fill);
  const grid=new THREE.GridHelper(size*1.5,30,'#c4d1d9','#d7e1e7');grid.position.y=-.2;scene.add(grid);
  let frame=0;const request=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;renderer.render(scene,camera)})};
  const reset=(mode:'iso'|'top')=>{controls.target.set(0,0,0);camera.zoom=1;camera.up.set(0,1,0);camera.position.set(mode==='top'?0:-size*.65,mode==='top'?size*1.4:size*.94,mode==='top'?.001:size*.83);camera.lookAt(0,0,0);camera.updateProjectionMatrix();controls.update();request()};
  const resize=()=>{const {width,height}=element.getBoundingClientRect();if(width<2||height<2)return;renderer.setSize(width,height,false);const aspect=width/height,vertical=size*(aspect<1?1.15/aspect:1.08);camera.left=-vertical*aspect/2;camera.right=vertical*aspect/2;camera.top=vertical/2;camera.bottom=-vertical/2;camera.updateProjectionMatrix();request()};
  const observer=new ResizeObserver(resize);observer.observe(element);controls.addEventListener('change',request);reset('iso');resize();
  engine.current={scene,camera,controls,renderer,built:null,reset,request,size};
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let start=[0,0];
  const down=(ev:PointerEvent)=>{start=[ev.clientX,ev.clientY]};
  const up=(ev:PointerEvent)=>{if(Math.hypot(ev.clientX-start[0],ev.clientY-start[1])>5||ev.button!==0)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((ev.clientX-rect.left)/rect.width*2-1,-(ev.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=engine.current?.built?ray.intersectObject(engine.current.built.root,true):[];const hit=hits.find(h=>h.object.userData.pick||h.object.userData.picks);pick.current(hit?(hit.instanceId!==undefined?hit.object.userData.picks[hit.instanceId]:hit.object.userData.pick):null)};
  const lost=(ev:Event)=>{ev.preventDefault();setError('三维显示已暂停。请切换到描图核对，或重新选择本层以加载。')};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('webglcontextlost',lost);
  return()=>{observer.disconnect();controls.removeEventListener('change',request);controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('webglcontextlost',lost);if(frame)cancelAnimationFrame(frame);engine.current?.built?.dispose();engine.current=null;grid.geometry.dispose();(grid.material as THREE.Material).dispose();sun.shadow.dispose();renderer.dispose();renderer.domElement.remove()};
 },[model]);
 useEffect(()=>{const e=engine.current;if(!e)return;if(e.built){e.scene.remove(e.built.root);e.built.dispose()}e.built=buildPlanScene(model,options);e.scene.add(e.built.root);e.request();},[model,options.wallHeight,options.furniture,options.circulation,options.inferred,options.byEvidence,options.rooms]);
 return <div className="plan-three-host" ref={host}>{error&&<div className="model-error" role="status">{error}</div>}<div className="three-compass" aria-hidden="true"><span>原图坐标参考</span><small>未核验真北</small></div><div className="three-instructions">拖动旋转 · 右键平移 · 滚轮缩放 · 点击查看构件</div></div>;
});


