'use client';
import {useRef,useState} from 'react';
import f1 from '@/lib/f1.json';
import {zones,poi,type Route} from '@/lib/study';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Minus,Plus,Maximize2,LocateFixed} from 'lucide-react';
export default function Plan({roomId,onRoom,routes,sequence,variant}:{roomId:string|null;onRoom:(id:string)=>void;routes:(Route|null)[];sequence:string[];variant:'a'|'b'}){
 const [zoom,setZoom]=useState(1),[center,setCenter]=useState([44550,32400]),[furniture,setFurniture]=useState(true),[labels,setLabels]=useState(true);
 const drag=useRef<{x:number;y:number;center:number[];moved:boolean}|null>(null);
 const width=97100/zoom,height=72800/zoom,color=variant==='a'?'#087f99':'#c16e16';
 const unique=[...new Set(sequence)];
 const reset=()=>{setZoom(1);setCenter([44550,32400]);};
 const locate=()=>{const r=f1.model.rooms.find(x=>x.id===roomId);if(r){setZoom(2.5);setCenter([(r.rect[0]+r.rect[2])/2,64800-(r.rect[1]+r.rect[3])/2]);}};
 return <><div className="map-controls"><div className="layer-switches"><label><Switch checked={furniture} onCheckedChange={setFurniture} aria-label="显示家具布置"/>家具</label><label><Switch checked={labels} onCheckedChange={setLabels} aria-label="显示房间标签"/>标签</label></div><div className="map-tools"><Button variant="ghost" size="icon" aria-label="缩小平面" onClick={()=>setZoom(Math.max(1,zoom-.5))}><Minus/></Button><span>{zoom.toFixed(1)}×</span><Button variant="ghost" size="icon" aria-label="放大平面" onClick={()=>setZoom(Math.min(5,zoom+.5))}><Plus/></Button><Button variant="ghost" size="icon" aria-label="查看完整平面" onClick={reset}><Maximize2/></Button><Button variant="ghost" size="icon" aria-label="定位选中房间" disabled={!roomId} onClick={locate}><LocateFixed/></Button></div></div>
 <svg viewBox={`${center[0]-width/2} ${center[1]-height/2} ${width} ${height}`} className="plan" aria-label="F1首层空间与公共路线；可拖动及点选房间" onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,center:[...center],moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect(),scale=Math.max(width/rect.width,height/rect.height),dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>5){drag.current.moved=true;setCenter([drag.current.center[0]-dx*scale,drag.current.center[1]-dy*scale]);}}} onPointerUp={()=>{setTimeout(()=>{drag.current=null},0)}} onPointerCancel={()=>{drag.current=null}}>
 <defs><pattern id="grid" width="8100" height="8100" patternUnits="userSpaceOnUse"><path d="M8100 0H0V8100" fill="none" stroke="#91acbb" strokeWidth="45" strokeDasharray="120 180"/></pattern><pattern id="void" width="700" height="700" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0V700" stroke="#b3c4cc" strokeWidth="120"/></pattern><marker id="route-arrow" markerWidth="5" markerHeight="5" refX="3" refY="2.5" orient="auto" markerUnits="strokeWidth"><path d="M0 0L4 2.5L0 5" fill="none" stroke={color} strokeWidth=".8"/></marker></defs>
 <g transform="translate(0 64800) scale(1 -1)"><polygon points={f1.model.footprint.map(p=>p.join(',')).join(' ')} fill="white" stroke="#59707e" strokeWidth="130"/><rect width="89100" height="64800" fill="url(#grid)" pointerEvents="none"/><polygon points={f1.model.void.map(p=>p.join(',')).join(' ')} fill="url(#void)" stroke="#b3c4cc" strokeWidth="80"/>
 {f1.model.rooms.map(r=><g key={r.id} role="button" tabIndex={0} aria-label={`${r.id} ${r.name}，${r.area_m2}平方米`} onPointerDown={e=>e.stopPropagation()} onClick={()=>{if(!drag.current?.moved)onRoom(r.id)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onRoom(r.id)}}}><title>{`${r.id} · ${r.name} · ${r.area_m2} ㎡`}</title><rect x={r.rect[0]} y={r.rect[1]} width={r.rect[2]-r.rect[0]} height={r.rect[3]-r.rect[1]} fill={zones[r.zone].color} stroke={roomId===r.id?'#0c6882':'white'} strokeWidth={roomId===r.id?300:30}/></g>)}
 {furniture&&f1.furniture.objects.map(o=><rect key={o.id} x={o.x-o.width/2} y={o.y-o.depth/2} width={o.width} height={o.depth} transform={`rotate(${o.rotation} ${o.x} ${o.y})`} fill={o.kind==='wheelchair_space'?'none':o.kind==='bench'?'#517c89':'#91a4ad'} fillOpacity={o.kind==='bench'?.9:.5} stroke={o.kind==='wheelchair_space'?'#0e8398':'#506b7b'} strokeWidth="55" strokeDasharray={o.kind==='wheelchair_space'?'120 100':undefined} pointerEvents="none"/>)}
 {f1.model.wallPolygons.map((w,i)=><path key={i} d={[w.points,...w.holes].map(p=>'M'+p.map(x=>x.join(' ')).join('L')+'Z').join(' ')} fill="#435765" fillRule="evenodd" pointerEvents="none"/>)}
 {f1.model.columns.map((c,i)=><rect key={i} x={c.x-300} y={c.y-300} width="600" height="600" fill="#263e4e" pointerEvents="none"/>)}
 {[26500,29700].map(y=>{const length=f1.model.params.floorHeightMm/Math.tan(Math.PI/6)+3000;return <g key={y} pointerEvents="none"><rect x={40500-length/2} y={y-900} width={length} height="1800" fill="#b7c7d0" stroke="#4d7184" strokeWidth="100"/>{Array.from({length:22},(_,i)=><line key={i} x1={40500-length/2+1500+i*(length-3000)/21} x2={40500-length/2+1500+i*(length-3000)/21} y1={y-700} y2={y+700} stroke="#68828f" strokeWidth="65"/>)}</g>})}
 {f1.model.doors.map((d,i)=>{const vertical=d.side==='E'||d.side==='W';return <line key={i} x1={d.x-(vertical?0:d.width/2)} x2={d.x+(vertical?0:d.width/2)} y1={d.y-(vertical?d.width/2:0)} y2={d.y+(vertical?d.width/2:0)} stroke="#65a998" strokeWidth="110" pointerEvents="none"/>})}
 {labels&&f1.model.rooms.map(r=><text key={r.id} transform={`translate(${(r.rect[0]+r.rect[2])/2} ${(r.rect[1]+r.rect[3])/2}) scale(1 -1)`} textAnchor="middle" fontSize={zoom>1.7?700:1000} fontWeight="500" fill="#203c4c" pointerEvents="none" paintOrder="stroke" stroke="white" strokeWidth="80" strokeOpacity=".8">{zoom>1.7?r.name:r.id}</text>)}
 {routes.filter(Boolean).map((r,i)=><g key={i} pointerEvents="none"><polyline points={r!.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="white" strokeWidth="520" strokeLinejoin="round"/><polyline points={r!.points.map(p=>p.join(',')).join(' ')} fill="none" stroke={color} strokeWidth="250" strokeLinejoin="round" strokeDasharray={variant==='b'?'550 230':undefined} markerEnd="url(#route-arrow)"/></g>)}
 {unique.map(id=>{const p=poi(id),order=sequence.map((x,i)=>x===id?i+1:null).filter(Boolean).join('/');return <g key={id} transform={`translate(${p.x} ${p.y}) scale(1 -1)`} pointerEvents="none"><circle r="980" fill={color} stroke="white" strokeWidth="200"/><text textAnchor="middle" dominantBaseline="central" fontSize={order.length>2?650:900} fill="white" fontWeight="650">{order}</text></g>})}</g></svg>
 <div className="plan-footer"><span>轴网 8.1 m · 北向待确认 · 拖动平移</span><span>放大后显示完整房名</span></div><div className="zone-legend">{Object.entries(zones).map(([k,v])=><span key={k}><i style={{background:v.color}}/>{v.name}</span>)}<span><i className="door-key"/>门洞</span></div></>
}
