'use client';
import {useState} from 'react';
import {svgImageFallback} from './source-image';
import {type PlanModel,roomColors,furnitureNames} from '@/lib/plan-model';
import {type PickInfo,type SceneOptions} from '@/lib/plan-scene';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Minus,Plus,Focus} from 'lucide-react';
export function PlanOverlay({model,options,onPick}:{model:PlanModel;options:SceneOptions;onPick:(p:PickInfo|null)=>void}){const [zoom,setZoom]=useState(1),[opacity,setOpacity]=useState(.65);const lines=(p:number[][])=>p.map(a=>a.join(',')).join(' ');return <><div className="overlay-toolbar"><span>底图透明度</span><Slider aria-label="底图透明度" min={0} max={1} step={.05} value={[opacity]} onValueChange={v=>setOpacity(Array.isArray(v)?v[0]:v)}/><Button variant="ghost" size="icon" aria-label="缩小描图" onClick={()=>setZoom(Math.max(1,zoom-.5))}><Minus/></Button><span>{zoom.toFixed(1)}×</span><Button variant="ghost" size="icon" aria-label="放大描图" onClick={()=>setZoom(Math.min(6,zoom+.5))}><Plus/></Button><Button variant="ghost" size="icon" aria-label="整张描图" onClick={()=>setZoom(1)}><Focus/></Button></div><div className="model-overlay-scroll"><svg viewBox={`0 0 ${model.width} ${model.height}`} style={{width:`${zoom*100}%`,maxWidth:'none'}} role="img" aria-label={`${model.label} 几何描图和家具位置与原图逐像素叠合`}><image onError={svgImageFallback} href={model.image} width={model.width} height={model.height} opacity={opacity}/>{options.rooms&&model.rooms.map(r=><polygon key={r.id} points={lines(r.polygon)} fill={roomColors[r.kind]} fillOpacity=".2" stroke="#438699" strokeWidth=".7" onClick={()=>onPick({kind:'room',id:r.id,label:r.label,evidence:r.evidence})}><title>{r.label}</title></polygon>)}{model.walls.map((w,i)=><line key={i} x1={w.a[0]} y1={w.a[1]} x2={w.b[0]} y2={w.b[1]} stroke={w.evidence==='inferred'?'#b68746':'#2e6479'} strokeWidth={Math.max(1.4,w.thickness??1.4)} strokeOpacity=".75"/>)}{model.openings.filter(o=>options.inferred||o.evidence!=='inferred').map((o,i)=><line key={i} x1={o.a[0]} y1={o.a[1]} x2={o.b[0]} y2={o.b[1]} stroke={o.kind==='door'?'#de9e4c':'#3ab0c4'} strokeWidth="3.5"/>)}{options.furniture&&model.furniture.filter(f=>options.inferred||f.evidence!=='inferred').map(f=><g key={f.id} transform={`translate(${f.x} ${f.y}) rotate(${f.rotation})`} onClick={()=>onPick({kind:'furniture',id:f.id,label:furnitureNames[f.type],evidence:f.evidence,detail:f.evidence==='inferred'?'推定家具布置，不代表现状':'参照可辨图上符号'})}><rect x={-f.w/2} y={-f.d/2} width={f.w} height={f.d} rx={Math.min(f.w,f.d)*.12} fill={f.evidence==='inferred'?'#d5a764':'#43a1ad'} fillOpacity=".7" stroke={f.evidence==='inferred'?'#9e712d':'#1a7885'} strokeWidth=".8"/>{['bed','exam','operating'].includes(f.type)&&<rect x={f.w>f.d?f.w*.25:-f.w*.35} y={f.w>f.d?-f.d*.35:-f.d*.4} width={f.w>f.d?f.w*.15:f.w*.7} height={f.w>f.d?f.d*.7:f.d*.15} rx="1" fill="white"/>}<title>{furnitureNames[f.type]} · {f.evidence==='inferred'?'推定':'图示'} · {f.id}</title></g>)}</svg></div></>}


