'use client';
import {publicUrl} from '@/lib/public-url';
import {useState,useEffect,useRef} from 'react';
import {flushSync} from 'react-dom';
import f1 from '@/lib/f1.json';
import {cases,study,poi,zones,fmt,radii,formatReport} from '@/lib/study';
import Plan from './plan';
import {Evidence,SourceData,DataTable} from './evidence';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Layers3,ArrowUpRight,ArrowRight,Download,Route,MoveUpRight,Check,FileCheck2,RotateCcw,Focus,Clock3,Box,Info} from 'lucide-react';
type Tab='flow'|'evidence'|'data'|'model';
function Picker({label,value,onChange,items}:{label:string;value:string;onChange:(s:string)=>void;items:{value:string;label:string}[]}){return <Select value={value||null} onValueChange={v=>{if(v)onChange(v)}} items={items}><SelectTrigger aria-label={label}><SelectValue placeholder="选择房间"/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function save(content:string,name:string){const u=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
export default function Workspace(){
 const [id,setId]=useState('outpatient'),[radius,setRadius]=useState(300),[speed,setSpeed]=useState(60),[variant,setVariant]=useState<'a'|'b'>('a'),[tab,setTab]=useState<Tab>('flow'),[roomId,setRoomId]=useState<string|null>(null),[leg,setLeg]=useState<number|null>(null);
 const c=cases.find(x=>x.id===id)!,result=study(id,radius,speed),active=result[variant],room=f1.model.rooms.find(x=>x.id===roomId);
 const choose=(nextId:string)=>{const next=cases.find(x=>x.id===nextId)!;setId(nextId);setRadius(next.radius);setSpeed(next.speed);setLeg(null);setVariant('a');};
 const baseline=study(id,300,speed);
 const api=useRef({result,setId,setRadius,setSpeed,setTab,setLeg});api.current={result,setId,setRadius,setSpeed,setTab,setLeg};
 useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as unknown as {modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(error=>console.warn('F1 tool registration failed',error));}catch(error){console.warn('F1 tool registration failed',error)}};
 const concise=(r:ReturnType<typeof study>)=>({caseId:r.caseId,radiusMm:r.radiusMm,speedMMin:r.speedMMin,aMeters:r.a.distanceM,bMeters:r.b.distanceM,conditionalSavedMeters:r.savedM,scope:'F1 public-node horizontal movement only; operating assumptions unconfirmed.'});
 register({name:'get_f1_analysis',title:'读取首层路径论证',description:'读取当前首层示例、参数及条件性 A/B 路程；不修改状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('此工具仅接受空对象');return concise(api.current.result)}});
 register({name:'configure_f1_analysis',title:'设置并计算首层情景',description:'选择一个既有路径情景、圆盘半径与假设速度，更新页面并返回水平距离比较。',inputSchema:{type:'object',properties:{caseId:{type:'string',enum:cases.map(x=>x.id)},radiusMm:{type:'integer',enum:radii},speedMMin:{type:'number',minimum:20,maximum:90}},required:['caseId','radiusMm','speedMMin'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('请输入对象');const x=input as Record<string,unknown>;if(Object.keys(x).some(k=>!['caseId','radiusMm','speedMMin'].includes(k))||typeof x.caseId!=='string'||typeof x.radiusMm!=='number'||typeof x.speedMMin!=='number')throw Error('参数格式错误');const next=study(x.caseId,x.radiusMm,x.speedMMin);flushSync(()=>{api.current.setId(next.caseId);api.current.setRadius(next.radiusMm);api.current.setSpeed(next.speedMMin);api.current.setTab('flow');api.current.setLeg(null);});return concise(next)}});
 return()=>lifecycle.abort();},[]);
 return <main><header className="topbar"><div className="brand"><Layers3 size={24}/><strong>综合医院<span>F1 方案论证</span></strong></div><div className="source-tag"><span className="status-dot"/>用户提供方案 · 项目身份待确认</div><Button variant="ghost" className="top-link" onClick={()=>save(formatReport(),'F1_三组路径论证.md')}><Download size={16}/>下载论证</Button></header>
 <div className="heading"><div><div className="eyebrow">PROJECT / FIRST FLOOR</div><h1>从这张图纸，开始论证。</h1><p>同一份首层方案，三组路径情景；保留原坐标与通行边界。</p></div><div className="compact-stats"><span><b>76</b>房间</span><span><b>93</b>门洞</span><span><b>8.1 <small>m</small></b>轴网</span><span><b>1,352</b>已计算节点路线</span></div></div>
 <Tabs value={tab} onValueChange={v=>setTab(v as Tab)} className="main-tabs"><div className="tab-bar"><TabsList variant="line"><TabsTrigger value="flow"><Route/>平面与流线</TabsTrigger><TabsTrigger value="evidence"><FileCheck2/>三组论证</TabsTrigger><TabsTrigger value="data"><Layers3/>数据与边界</TabsTrigger><TabsTrigger value="model"><Box/>原始 3D</TabsTrigger></TabsList><span className="verified"><Check size={14}/>169 项原文件基准核对通过</span></div>
 <TabsContent value="flow"><div className="work-grid"><aside className="panel scenario-panel"><div className="eyebrow">选择路径情景</div>{cases.map((x,i)=><Button key={x.id} aria-pressed={id===x.id} variant={id===x.id?'default':'outline'} className="case-button" onClick={()=>choose(x.id)}><span>0{i+1}</span><div>{x.short}<small>{x.tag}</small></div></Button>)}<div className="parameter"><label>圆盘通行半径 <span>几何参数</span></label><Picker label="圆盘通行半径" value={String(radius)} onChange={v=>{setRadius(Number(v));setLeg(null)}} items={radii.map(r=>({value:String(r),label:`${r} mm`}))}/><p>不等同于人体或轮椅合规尺寸。</p></div><div className="parameter"><label>假设移动速度 <b>{speed} m/min</b></label><Slider aria-label="假设移动速度，米每分钟" min={20} max={90} step={1} value={[speed]} onValueChange={v=>setSpeed(Array.isArray(v)?v[0]:v)}/><p>只换算纯移动时间，不含任何等待。</p></div><Button variant="ghost" className="reset-button" onClick={()=>choose(id)}><RotateCcw/>恢复示例参数</Button><div className="scope-note"><b>建模范围：首层公共到达</b><p>检查与诊疗空间不作借道。其他楼层、病房、急诊和手术部资料待补充。</p></div></aside>
 <div className="center-stack"><section className="metric-strip" aria-live="polite"><div><span><Route size={15}/>路径链水平距离</span><b>{fmt(active.distanceM)}<small>m</small></b><em>{variant==='a'?'A · 保留现场办理':'B · 所需办理已完成'}</em></div><div><span><Clock3 size={15}/>设定速度下纯移动</span><b>{fmt(active.minutes,2)}<small>min</small></b><em>不含候诊、检查与乘梯</em></div><div className="saving"><span><MoveUpRight size={15}/>B 条件性省行</span><b>{fmt(result.savedM)}<small>m</small></b><em>比 A 减少 {fmt(result.percent)}%</em></div></section>
 <section className="panel plan-panel"><div className="panel-title"><div><b>首层平面 / 原坐标复原</b><small>{leg===null?'完整路径链':`仅显示第 ${leg+1} 段`} · {variant==='a'?'A 现场办理':'B 有条件略过办理点'}</small></div><Tabs value={variant} onValueChange={v=>{setVariant(v as 'a'|'b');setLeg(null)}}><TabsList><TabsTrigger value="a">A 现场办理</TabsTrigger><TabsTrigger value="b">B 已完成办理</TabsTrigger></TabsList></Tabs></div><Plan roomId={roomId} onRoom={setRoomId} routes={leg===null?active.legs:[active.legs[leg]]} sequence={leg===null?active.sequence:active.sequence.slice(leg,leg+2)} variant={variant}/></section>
 <section className="panel segment-panel"><div className="panel-title"><b>逐段核查</b>{leg!==null?<Button variant="ghost" onClick={()=>setLeg(null)}>显示整条路径</Button>:<span>点选一段，在图上定位</span>}</div><div className="route-steps">{active.sequence.map((x,i)=><span key={`${x}-${i}`}><i>{i+1}</i>{poi(x).name}{i<active.sequence.length-1&&<ArrowRight size={14}/>}</span>)}</div><DataTable headers={['路段','到达节点','可行路径','直线参考','绕行系数']} rows={active.legs.map((r,i)=>[<Button key={i} variant={leg===i?'default':'outline'} size="sm" onClick={()=>setLeg(leg===i?null:i)}><Focus size={14}/>{i+1}</Button>,`${poi(active.sequence[i]).name} → ${poi(active.sequence[i+1]).name}`,`${fmt(r?.distanceM)} m`,`${fmt(r?.directM)} m`,r?`${fmt(r.distanceM/r.directM,2)}×`:'不可达'])}/><p className="footnote">直线距离只作几何参照，可能穿墙；图上路径沿公共通道计算，不进入诊室或机房。</p></section></div>
 <aside className="panel inspector"><div className="eyebrow">本组设计问题</div><h2>{c.title}</h2><p className="question">{c.question}</p><div className="insight-number"><span>A → B</span><b>−{fmt(result.percent)}<small>%</small></b><span>公共水平移动 · 条件性差值</span></div><div className="annotation"><b>B 的成立条件</b><p>{c.proposal}</p></div><div className="annotation"><b>包络参数的影响</b><p>当前 {radius} mm 相对 300 mm 基准，A 路程差值为 {fmt(result.a.distanceM!==null&&baseline.a.distanceM!==null?result.a.distanceM-baseline.a.distanceM:null,2)} m。此结果不代替轮椅转弯、门扇和陪护空间核查。</p></div><div className="annotation"><b>空间档案</b><Picker label="选择房间查看档案" value={roomId??''} onChange={setRoomId} items={f1.model.rooms.map(r=>({value:r.id,label:`${r.id} · ${r.name}`}))}/>{room?<div className="room-card"><strong>{room.name}<span>{room.id}</span></strong><div><b>{room.area_m2}</b> ㎡ <small>文件所列净面积</small></div><p>{zones[room.zone].name} · 原坐标 ({room.rect[0]}, {room.rect[1]})–({room.rect[2]}, {room.rect[3]}) mm</p><p>用途按源文件保留；带 * 的项目为暂拟。</p></div>:<p>点击平面中的房间，或从清单选择。</p>}</div></aside></div></TabsContent>
 <TabsContent value="evidence"><Evidence onChoose={next=>{choose(next);setTab('flow')}}/></TabsContent>
 <TabsContent value="data"><SourceData onRoom={r=>{setRoomId(r);setTab('flow')}}/></TabsContent>
 <TabsContent value="model"><div className="model-wrap"><div className="model-notice"><Info size={19}/><p>这里保留原文件的 3D、测量和图层功能。模型中的交互试改不回写本页基准分析；路线比较仍使用导入时的公共净空场。</p><a href={publicUrl('/source-f1.html')} target="_blank" rel="noreferrer">独立窗口<ArrowUpRight size={16}/></a></div>{tab==='model'&&<iframe src={publicUrl('/source-f1.html')} title="用户提供的原始 F1 离线三维模型" className="original-model" sandbox="allow-scripts allow-same-origin allow-downloads"/>}</div></TabsContent>
 </Tabs><footer className="lab-footer"><span>F1 / 综合医院方案论证</span><span>用户方案数据 · 路径情景假设 · 可复现计算</span><span>2026.09 · 首层研究范围</span></footer></main>
}
