export type Point=[number,number];
export type FurnitureType='bed'|'chair'|'desk'|'cabinet'|'exam'|'operating'|'toilet'|'sink'|'sofa'|'counter'|'scanner'|'stair'|'lift'|'escalator';
export type Furnishing={id:string;type:FurnitureType;x:number;y:number;w:number;d:number;rotation:number;yHeight?:number;evidence:'symbol'|'inferred';roomId?:string;note?:string;stairLayout?:'straight'|'dogleg';rise?:number};
export type PlanModel={id:string;project:string;label:string;levels:number[];image:string;width:number;height:number;unitsPerPixel:number;scaleStatus:'assumed'|'scale-bar';scaleNote:string;slabs:{outline:Point[];holes:Point[][]}[];walls:{a:Point;b:Point;thickness?:number;evidence:'traced'|'inferred'}[];rooms:{id:string;label:string;polygon:Point[];kind:'ward'|'clinic'|'support'|'public'|'operating'|'toilet'|'unknown';evidence:'traced'|'inferred'}[];openings:{kind:'door'|'window';a:Point;b:Point;evidence:'traced'|'inferred'}[];furniture:Furnishing[];notes:string[]};
export const furnitureNames:Record<FurnitureType,string>={bed:'病床',chair:'座椅',desk:'桌台',cabinet:'柜体',exam:'诊查床',operating:'手术台',toilet:'坐便器',sink:'洗手盆',sofa:'长椅 / 沙发',counter:'服务台',scanner:'检查设备',stair:'楼梯',lift:'电梯',escalator:'自动扶梯'};
export const circulationTypes=['stair','lift','escalator'] as const;
export function isCirculation(type:string){return (circulationTypes as readonly string[]).includes(type)}
export function furnishingDetail(f:Furnishing){return [f.note,f.evidence==='symbol'?'平面位置 / 类型参照图示；三维构造为简化表达。':'推定位置 / 布置，待项目资料核实。',isCirculation(f.type)?'梯段、轿厢门、扶手和提升高度用于识别设施，不代表实测尺寸、真实上下行方向或跨层连接。':''].filter(Boolean).join(' ')}
export const roomColors:Record<string,string>={ward:'#d8e9ee',clinic:'#d8e5ed',support:'#e5e4e9',public:'#eee6d8',operating:'#d9e9e1',toilet:'#deebeb',unknown:'#e8ecef'};
export function insidePolygon(p:Point,polygon:Point[]){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
export function furnitureCorners(f:Furnishing):Point[]{const a=f.rotation*Math.PI/180;return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>[f.x+x*f.w/2*Math.cos(a)-y*f.d/2*Math.sin(a),f.y+x*f.w/2*Math.sin(a)+y*f.d/2*Math.cos(a)]);}
export function modelBounds(model:PlanModel){const points=model.slabs.flatMap(s=>s.outline);return {minX:Math.min(...points.map(p=>p[0])),minY:Math.min(...points.map(p=>p[1])),maxX:Math.max(...points.map(p=>p[0])),maxY:Math.max(...points.map(p=>p[1]))};}
export function modelCounts(m:PlanModel){return {walls:m.walls.length,rooms:m.rooms.length,doors:m.openings.filter(o=>o.kind==='door').length,windows:m.openings.filter(o=>o.kind==='window').length,furniture:m.furniture.filter(f=>!isCirculation(f.type)).length,inferred:m.furniture.filter(f=>f.evidence==='inferred'&&!isCirculation(f.type)).length,symbols:m.furniture.filter(f=>f.evidence==='symbol'&&!isCirculation(f.type)).length,stairs:m.furniture.filter(f=>f.type==='stair').length,lifts:m.furniture.filter(f=>f.type==='lift').length,escalators:m.furniture.filter(f=>f.type==='escalator').length};}
export function downloadData(data:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
