import fs from 'node:fs';
import assert from 'node:assert/strict';
import {hospitals,journeyStats} from '../lib/projects.ts';
import {DEFAULTS,SEEDS,experiment,simulate,requestsFor,validateOptions,type Options} from '../lib/vertical-sim.ts';
const results=[];let checkedRecords=0,checkedTrips=0;
for(const h of hospitals){
 for(const f of h.floors){for(const s of f.sources)assert(h.sources.some(x=>x.id===s),`${h.id} source ${s}`);if(f.image)assert(fs.existsSync('public'+f.image),f.image);}
 for(const j of h.journeys){assert.equal(j.labels.length,j.floors.length);assert(j.floors.every(l=>h.floors.some(f=>f.level===l)));assert(journeyStats(j).rides>0);}
 for(const demand of [.6,1,1.4]){const options={...DEFAULTS,demand},e=experiment(h.id,options);assert(e.runs.every(r=>r.a.served===r.b.served));results.push(e);}
 const requests=requestsFor(h.id,DEFAULTS,SEEDS[0]);assert.deepEqual(requests,requestsFor(h.id,DEFAULTS,SEEDS[0]));
 for(const mode of ['shared','dedicated'] as const){const output=simulate(h.id,DEFAULTS,requests,mode,true),records=output.records!;checkedRecords+=records.length;
  assert.equal(records.length,requests.length);assert.equal(new Set(records.map(r=>r.id)).size,requests.length);
  for(let car=0;car<DEFAULTS.fleet;car++){const groups=new Map<number,typeof records>();for(const r of records.filter(r=>r.car===car)){if(!groups.has(r.pickup))groups.set(r.pickup,[]);groups.get(r.pickup)!.push(r);}let previousEnd=-Infinity;for(const [pickup,group] of [...groups].sort((a,b)=>a[0]-b[0])){assert(pickup>=previousEnd);assert(group.length<=12);assert(group.every(r=>r.from===group[0].from&&r.to===group[0].to&&r.kind===group[0].kind));if(group[0].kind==='bed')assert.equal(group.length,1);if(mode==='dedicated')assert(group.every(r=>r.kind===(car<DEFAULTS.dedicated?'bed':'public')));previousEnd=group[0].completed;checkedTrips++;}}
 }
}
assert.throws(()=>validateOptions({} as Options));assert.throws(()=>validateOptions({...DEFAULTS,dedicated:4}));assert.throws(()=>validateOptions({...DEFAULTS,demand:NaN}));
const single=simulate('dushu',DEFAULTS,[{id:0,at:0,from:1,to:2,kind:'public'}],'shared',true);assert.equal(single.records![0].pickup,10);assert.equal(single.records![0].completed,44);
assert(Number.isNaN(single.bedP90),'Missing bed observations must not become zero wait');
const pairedRuns=results.length*SEEDS.length,modelRuns=pairedRuns*2;
const audit={date:'2026-09-08',hospitals:3,demandLevels:[.6,1,1.4],seedCount:SEEDS.length,pairedRuns,modelRuns,checkedRecords,checkedTrips,checks:['same requests A/B','all requests assigned unique completion','no overlapping trips per car','public batch <=12 same origin/destination','bed trip exclusive','B bank roles respected','deterministic generation','invalid options rejected','single-trip analytic oracle','all referenced floor/source/assets exist']};
const compact=results.filter(x=>x.options.demand===1);fs.writeFileSync('lib/vertical-defaults.json',JSON.stringify(compact));
fs.writeFileSync('public/multifloor-audit.json',JSON.stringify(audit,null,2));fs.writeFileSync('public/multifloor-results.json',JSON.stringify(results,null,2));
fs.writeFileSync('public/multifloor-results.csv','\ufeff'+['hospital,demand,seed,variant,public_p90_s,bed_p90_s,public_mean_s,bed_mean_s,public_count,bed_count,trips,utilization_pct,clearance_min',...results.flatMap(e=>e.runs.flatMap(r=>(['a','b'] as const).map(v=>[e.id,e.options.demand,r.seed,v,r[v].publicP90,r[v].bedP90,r[v].publicMean,r[v].bedMean,r[v].publicCount,r[v].bedCount,r[v].trips,r[v].utilization,r[v].clearanceMinutes].join(','))))].join('\n'));
const report=['# 多层综合医院 · 公开项目设计研究','',`完成于 ${audit.date}；3 个真实项目，3 个假设需求倍率，12 个配对种子；共 ${modelRuns} 次仿真。`,'','## 事实和情景分开','楼层、图纸和建设规模按列明来源；医院实际电梯、到达量、运行控制和门禁并未获取。这里的 A/B 是设计运行实验，均不是对医院现状的复现或预测。','A：4 台共享服务池；B：1 台严格床梯 + 3 台公众梯；不允许跨池借梯。3h 泊松请求，公众 360 人次/h、床转运 24 次/h；同起终点公众最多 12 人拼梯，床独占。','南京按剖面标高；其他项目按 4 m 层高/编号间距假设。运行参数为每 4m 用 4s；空驶接人后开门 10s，上客公众15s/床40s，目的层卸载15s。不模拟加减速、中途停站、楼梯扶梯、水平步行及完整临床服务。','请求相互独立，不形成随前次完成而推进的完整患者链；OD组合等概率，缺少实际流量权重。','P90是每个种子内分位数，再对12次求均值；区间为配对 B−A 的 t 区间，仅反映此模型的随机波动。','',...hospitals.flatMap(h=>{const e=compact.find(x=>x.id===h.id)!;return [`## ${h.name}`,`${h.phase}。${h.bedLabel}；${h.areaLabel}。${h.scope}`,'',...h.notes.map(x=>'- '+x),'','### 楼层事实',...h.floors.map(f=>`- ${f.label} ${f.title}：${f.functions.join('、')}。${f.note??''}`),'','### 跨层路径情景',...h.journeys.map(j=>`- ${j.title}：${j.labels.join(' → ')}；${journeyStats(j).rides}次换层。${j.note}`),'','### 默认运行实验（均为假设参数）',`- 公众候梯 P90：A ${e.a.publicP90.toFixed(1)}s → B ${e.b.publicP90.toFixed(1)}s。`,`- 床转运候梯 P90：A ${e.a.bedP90.toFixed(1)}s → B ${e.b.bedP90.toFixed(1)}s。`,`- B−A 床转运 P90 配对95%区间：[${e.delta.bedP90.low.toFixed(1)}, ${e.delta.bedP90.high.toFixed(1)}]s。`,'严格分工的代价必须同时查看：一类受益不能证明整体更优；闲置专梯与公众积压可同时发生。','',...h.sources.map(s=>`- [${s.title}](${s.url})，${s.date}，${s.kind}。${s.note}`),''];}),'## 下一步项目资料','原始带尺度 CAD/BIM、功能房间与实际门禁、各梯尺寸/载荷/速度/停靠、按时段的起终点请求、真实床转运与陪护规则、现场候梯样本。获得这些后再标定交通与空间模型。'];
fs.writeFileSync('public/multifloor-study.md',report.join('\n'));console.log(JSON.stringify({audit,baseline:compact.map(e=>({id:e.id,publicA:e.a.publicP90,publicB:e.b.publicP90,bedA:e.a.bedP90,bedB:e.b.bedP90}))},null,2));
