import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {buildPlanScene,exportableScene} from '../lib/plan-scene.ts';
import {type PlanModel,type Point,modelCounts,insidePolygon,furnitureCorners} from '../lib/plan-model.ts';
import {hospitals} from '../lib/projects.ts';

// GLTFExporter uses the browser FileReader API. This offline writer only reads local Blob buffers.
Object.defineProperty(globalThis,'FileReader',{value:class {result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;readAsArrayBuffer(blob:Blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.()})}}});
const out=path.resolve('public/models');
const selected=process.argv.slice(2);const projects=selected.length?selected:['dushu','nanjing','hongkong'];
const manifest:unknown[]=[];let totalFurniture=0,totalRooms=0,totalWalls=0,totalInstances=0;
function validPoint(p:Point,m:PlanModel){assert.equal(p.length,2);assert(p.every(Number.isFinite));assert(p[0]>=0&&p[0]<=m.width&&p[1]>=0&&p[1]<=m.height,`${m.id}: point outside source ${p}`)}
for(const project of projects){const models=JSON.parse(fs.readFileSync(path.join(out,project+'.json'),'utf8')) as PlanModel[];const expected=[...new Set(hospitals.find(h=>h.id===project)!.floors.filter(f=>f.image).map(f=>f.image))];assert.equal(models.length,expected.length,`${project}: every unique floor plan must have a model`);assert.deepEqual(new Set(models.map(m=>m.image)),new Set(expected));
 for(const model of models){assert(model.id.startsWith(project));assert.equal(model.project,project);assert(model.unitsPerPixel>0&&model.unitsPerPixel<1);assert(model.width>100&&model.height>100);assert(model.slabs.length&&model.walls.length&&model.rooms.length&&model.furniture.length);assert(model.notes.length&&model.scaleNote.length);assert(['assumed','scale-bar'].includes(model.scaleStatus));
  const coverage=hospitals.find(h=>h.id===project)!.floors.filter(f=>f.image===model.image).map(f=>f.level);assert.deepEqual(new Set(model.levels),new Set(coverage));
  for(const slab of model.slabs){assert(slab.outline.length>=3);for(const p of [slab.outline,...slab.holes].flat())validPoint(p,model)}
  for(const w of model.walls){validPoint(w.a,model);validPoint(w.b,model);assert(Math.hypot(w.a[0]-w.b[0],w.a[1]-w.b[1])>.001);assert(['traced','inferred'].includes(w.evidence));}
  for(const o of model.openings){validPoint(o.a,model);validPoint(o.b,model);assert(['traced','inferred'].includes(o.evidence));}
  const roomIds=new Set(model.rooms.map(r=>r.id));assert.equal(roomIds.size,model.rooms.length);for(const r of model.rooms){assert(r.polygon.length>=3);for(const p of r.polygon)validPoint(p,model);}
  const furnitureIds=new Set(model.furniture.map(f=>f.id));assert.equal(furnitureIds.size,model.furniture.length);let outside=0,outsideRoom=0;
  for(const f of model.furniture){validPoint([f.x,f.y],model);assert(f.w>0&&f.d>0&&Number.isFinite(f.rotation));assert(['symbol','inferred'].includes(f.evidence));assert(!f.roomId||roomIds.has(f.roomId),`${model.id} missing furniture room ${f.roomId}`);const corners=furnitureCorners(f);if(corners.some(p=>!model.slabs.some(s=>insidePolygon(p,s.outline)&&!s.holes.some(h=>insidePolygon(p,h)))))outside++;const r=model.rooms.find(r=>r.id===f.roomId);if(r&&corners.some(p=>!insidePolygon(p,r.polygon)))outsideRoom++;}
  assert.equal(outside,0,`${model.id}: furniture footprint outside slab or within courtyard`);assert.equal(outsideRoom,0,`${model.id}: furniture outside assigned room`);
  const options={wallHeight:3.2,furniture:true,inferred:true,byEvidence:true,rooms:true};const built=buildPlanScene(model,options);built.root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(built.root);assert(!bounds.isEmpty());assert([bounds.min.x,bounds.min.y,bounds.min.z,bounds.max.x,bounds.max.y,bounds.max.z].every(Number.isFinite));let instances=0;
  built.root.traverse(o=>{if(o instanceof THREE.InstancedMesh){instances+=o.count;assert.equal(o.userData.picks.length,o.count);for(let i=0;i<o.count;i++){const info=o.userData.picks[i];if(info.kind!=='furniture')continue;const f=model.furniture.find(f=>f.id===info.id)!;const matrix=new THREE.Matrix4();o.getMatrixAt(i,matrix);const angle=f.rotation*Math.PI/180;for(const xx of [-.5,.5])for(const zz of [-.5,.5]){const v=new THREE.Vector3(xx,0,zz).applyMatrix4(matrix);const px=v.x/model.unitsPerPixel+built.center.x-f.x,py=v.z/model.unitsPerPixel+built.center.y-f.y;const localX=px*Math.cos(angle)+py*Math.sin(angle),localY=-px*Math.sin(angle)+py*Math.cos(angle);assert(Math.abs(localX)<=f.w/2+1e-3&&Math.abs(localY)<=f.d/2+1e-3,`${model.id}/${f.id}: exported part outside recorded furniture footprint`)}}}if(o instanceof THREE.Mesh){const p=o.geometry.getAttribute('position');for(let i=0;i<p.array.length;i++)assert(Number.isFinite(p.array[i]));}});
  const binary=await new GLTFExporter().parseAsync(exportableScene(built.root),{binary:true}) as ArrayBuffer;const buffer=Buffer.from(binary);assert.equal(buffer.toString('ascii',0,4),'glTF');assert.equal(buffer.readUInt32LE(4),2);assert.equal(buffer.readUInt32LE(8),buffer.length);const jsonLength=buffer.readUInt32LE(12),gltf=JSON.parse(buffer.toString('utf8',20,20+jsonLength).trim());assert.equal(gltf.asset.version,'2.0');assert(gltf.nodes.length>0);assert(gltf.meshes.length>0);assert(!gltf.extensionsRequired?.includes('EXT_mesh_gpu_instancing'));
  fs.writeFileSync(path.join(out,model.id+'.glb'),buffer);const counts=modelCounts(model);manifest.push({id:model.id,project:model.project,label:model.label,levels:model.levels,image:model.image,glb:`/models/${model.id}.glb`,scaleStatus:model.scaleStatus,counts,geometryInstances:instances,bytes:buffer.length,checks:{sourceAndFloorCoverage:true,sourceImageIncluded:fs.existsSync(path.join("public",model.image)),finiteGeometry:true,furnitureWithinSlabAndOutsideCourtyards:outside===0,furnitureWithinAssignedRooms:outsideRoom===0,glbHeaderAndScene:true}});totalFurniture+=counts.furniture;totalRooms+=counts.rooms;totalWalls+=counts.walls;totalInstances+=instances;built.dispose();console.log(`${model.id}: ${counts.rooms} rooms, ${counts.furniture} furnishings, ${instances} mesh parts, ${(buffer.length/1048576).toFixed(2)} MB GLB`);
 }
}
// A closed wall, door and window oracle catches wrong axes and visually covered-but-not-cut openings.
const oracle:PlanModel={id:'fixture',project:'fixture',label:'fixture',levels:[1],image:'',width:120,height:120,unitsPerPixel:.1,scaleStatus:'assumed',scaleNote:'fixture',slabs:[{outline:[[0,0],[120,0],[120,120],[0,120]],holes:[]}],rooms:[],furniture:[],notes:[],walls:[{a:[0,60],b:[120,60],evidence:'traced'}],openings:[{kind:'door',a:[20,60],b:[35,60],evidence:'inferred'},{kind:'window',a:[70,60],b:[90,60],evidence:'traced'}]};
const scene=buildPlanScene(oracle,{wallHeight:3.2,furniture:true,inferred:true,byEvidence:true,rooms:true});scene.root.updateMatrixWorld(true);const walls=scene.root.getObjectByName('walls')!;function wallHit(x:number,y:number){return new THREE.Raycaster(new THREE.Vector3((x-60)*.1,y,-2),new THREE.Vector3(0,0,1)).intersectObject(walls,true).length>0}assert(!wallHit(27,1),'door must be a true wall opening');assert(wallHit(27,2.6),'door lintel must remain');assert(!wallHit(80,1.4),'window must be a true opening');assert(wallHit(80,.5),'window sill must remain');assert(wallHit(10,1),'unbroken wall must remain');scene.dispose();
const audit={generatedAt:new Date().toISOString(),scope:'Approximate image-derived models, with inferred furniture explicitly tagged. No as-built certification or real procurement quantities.',projects,modelCount:manifest.length,totals:{rooms:totalRooms,walls:totalWalls,furniture:totalFurniture,meshParts:totalInstances},oracle:{doorOpening:true,doorLintel:true,windowOpening:true,windowSill:true,solidWall:true},models:manifest};fs.writeFileSync(path.join(out,selected.length?'audit-'+projects.join('-')+'.json':'model-audit.json'),JSON.stringify(audit,null,2));console.log(JSON.stringify(audit.totals));


